with facts(topic, subject, title, summary, context, memory_hook) as (
values
  ('capitals','Canada','Ottawa','Ottawa is the capital of Canada. It sits in Ontario on the Ottawa River, directly across from Gatineau in Quebec.','Canada chose Ottawa as a compromise location between major English- and French-speaking centres.','Toronto is larger, but Ottawa is the capital.'),
  ('capitals','Australia','Canberra','Canberra is the capital of Australia. It is an inland, purpose-planned city in the Australian Capital Territory.','Canberra was selected partly as a compromise between rival cities Sydney and Melbourne.','Sydney and Melbourne competed; Canberra became the capital.'),
  ('capitals','New Zealand','Wellington','Wellington is the capital of New Zealand. It stands at the southern end of the North Island beside a large natural harbour.','Wellington is the world’s southernmost capital of a sovereign country.','Think windy Wellington at the bottom of the North Island.'),
  ('capitals','Brazil','Brasilia','Brasilia is the capital of Brazil. The modernist city was purpose-built inland and officially became the capital in 1960.','Its aircraft-like central plan is associated with planner Lucio Costa and architect Oscar Niemeyer.','Brazil built Brasilia as a new inland capital.'),
  ('capitals','Argentina','Buenos Aires','Buenos Aires is the capital of Argentina. The port city stands on the western shore of the Rio de la Plata.','It is known for tango, broad avenues, distinctive neighbourhoods, and strong European architectural influences.','Argentina and tango point to Buenos Aires.'),
  ('capitals','Chile','Santiago','Santiago is the capital of Chile. It lies in a valley between the Andes and Chilean Coast Range.','The Andes form a dramatic eastern backdrop and strongly shape the city’s geography and climate.','Chile’s long country is governed from Santiago beneath the Andes.'),
  ('capitals','Peru','Lima','Lima is the capital of Peru. It lies on the Pacific coast in a desert region and was founded by the Spanish in 1535.','The city is a major centre of Peruvian history and cuisine, while nearby Callao serves as its principal port.','Peru’s Pacific capital is Lima.'),
  ('capitals','Colombia','Bogota','Bogota is the capital of Colombia. It stands on a high plateau in the Andes at more than 2,600 metres above sea level.','Its altitude gives it a cooler climate than many places near the equator.','High in Colombia’s Andes: Bogota.'),
  ('capitals','Egypt','Cairo','Cairo is the capital of Egypt. The vast city lies beside the Nile and close to the pyramids of Giza.','It has been a major political and cultural centre of the Arab world for centuries.','Egypt, the Nile, and the pyramids lead to Cairo.'),
  ('capitals','Kenya','Nairobi','Nairobi is the capital of Kenya. It grew from a railway settlement and now borders a national park containing wild animals.','Nairobi National Park makes it unusual among world capitals by placing protected wildlife close to the city.','Kenya’s capital has a national park: Nairobi.'),
  ('capitals','Morocco','Rabat','Rabat is the capital of Morocco. It stands on the Atlantic coast at the mouth of the Bou Regreg River.','Casablanca is Morocco’s largest city, but Rabat is its political and administrative capital.','Casablanca is bigger; Rabat is the capital.'),
  ('capitals','Ethiopia','Addis Ababa','Addis Ababa is the capital of Ethiopia. Its name means “new flower” in Amharic.','The city hosts the headquarters of the African Union and is an important centre of continental diplomacy.','Ethiopia’s “new flower” is Addis Ababa.'),
  ('capitals','India','New Delhi','New Delhi is the capital of India. It forms one part of the much larger National Capital Territory of Delhi.','Designed in the British colonial period, it contains major government buildings and the ceremonial avenue Kartavya Path.','Delhi is the wider metropolis; New Delhi is the capital.'),
  ('capitals','Pakistan','Islamabad','Islamabad is the capital of Pakistan. It is a planned city at the foot of the Margalla Hills.','It replaced Karachi as the national capital during the 1960s.','Pakistan planned Islamabad beneath the Margalla Hills.'),
  ('capitals','Thailand','Bangkok','Bangkok is the capital of Thailand. The city developed around the Chao Phraya River and an extensive network of canals.','Its Thai ceremonial name is far longer, while Bangkok is the familiar international name.','Thailand’s river capital is Bangkok.'),
  ('capitals','Vietnam','Hanoi','Hanoi is the capital of Vietnam. The northern city is known for lakes, tree-lined streets, and a historic Old Quarter.','Ho Chi Minh City is larger, but Hanoi remains the political capital.','Ho Chi Minh City is larger; Hanoi is the capital.'),
  ('capitals','Indonesia','Jakarta','Jakarta is the capital associated with Indonesia in standard general knowledge. It is a huge coastal metropolis on the island of Java.','Indonesia has been developing Nusantara as a future capital, so this fact may change as the legal transition progresses.','Jakarta is the familiar current quiz answer; remember the Nusantara transition.'),
  ('capitals','South Korea','Seoul','Seoul is the capital of South Korea. The city stands on the Han River and forms the centre of a vast metropolitan area.','Historic palaces sit alongside major technology, entertainment, and business districts.','South Korea’s Han River capital is Seoul.'),
  ('capitals','Norway','Oslo','Oslo is the capital of Norway. It lies at the head of the Oslofjord and is surrounded by forested hills.','The city combines maritime history with quick access to woodland, islands, and winter recreation.','Norway’s fjord-side capital is Oslo.'),
  ('capitals','Finland','Helsinki','Helsinki is the capital of Finland. It occupies a peninsula and many islands on the Gulf of Finland.','Its coastal setting and ferries reflect Finland’s close relationship with the Baltic Sea.','Finland’s Baltic capital is Helsinki.'),
  ('capitals','Poland','Warsaw','Warsaw is the capital of Poland. Much of its historic centre was reconstructed after destruction during the Second World War.','The rebuilt Old Town is recognised by UNESCO as an outstanding example of near-total reconstruction.','Poland rebuilt its capital Warsaw after wartime destruction.'),
  ('capitals','Hungary','Budapest','Budapest is the capital of Hungary. The Danube separates historic Buda from Pest before the two sides were united as one city.','The river, thermal baths, and Parliament building are central to the city’s identity.','Buda plus Pest on the Danube makes Budapest.'),
  ('capitals','Greece','Athens','Athens is the capital of Greece. It is one of the world’s oldest cities and is overlooked by the Acropolis.','Ancient Athens profoundly influenced democracy, philosophy, drama, and Western political thought.','Greece, democracy, and the Acropolis point to Athens.'),
  ('capitals','Portugal','Lisbon','Lisbon is the capital of Portugal. It rises across hills beside the Tagus estuary near the Atlantic Ocean.','The city is known for yellow trams, tiled buildings, and its role in the Age of Exploration.','Portugal’s hilly Tagus capital is Lisbon.'),
  ('capitals','Ireland','Dublin','Dublin is the capital of Ireland. It stands at the mouth of the River Liffey on the east coast.','Its literary heritage includes writers such as James Joyce, Oscar Wilde, and Samuel Beckett.','Ireland’s Liffey and literary capital is Dublin.'),

  ('chemistry','hydrogen','Hydrogen','Hydrogen has the chemical symbol H and atomic number 1. It is the lightest and most abundant element in the universe.','Stars generate energy by fusing hydrogen nuclei into helium.','Hydrogen is first: atomic number 1 and symbol H.'),
  ('chemistry','helium','Helium','Helium has the symbol He and atomic number 2. It is a very light, unreactive noble gas.','Helium is used in balloons and cryogenics because it is light and has an extremely low boiling point.','Helium adds an e to hydrogen’s H: He.'),
  ('chemistry','carbon','Carbon','Carbon has the symbol C and atomic number 6. Its ability to form four bonds makes it central to organic chemistry and life.','Diamond and graphite are very different structures made entirely from carbon atoms.','Carbon is the backbone of life: symbol C.'),
  ('chemistry','nitrogen','Nitrogen','Nitrogen has the symbol N and atomic number 7. Nitrogen gas makes up about 78 percent of Earth’s atmosphere.','Living things need nitrogen to build proteins and DNA, but most cannot use atmospheric nitrogen directly.','Nitrogen dominates the atmosphere: N.'),
  ('chemistry','oxygen','Oxygen','Oxygen has the symbol O and atomic number 8. Oxygen gas supports respiration and combustion.','It makes up about 21 percent of Earth’s atmosphere and is also bound into water and rocks.','Oxygen is simply O.'),
  ('chemistry','sodium','Sodium','Sodium has the symbol Na and atomic number 11. It is a soft, highly reactive metal.','The symbol Na comes from the Latin-derived name natrium; sodium combines with chlorine in table salt.','Sodium’s surprising symbol is Na from natrium.'),
  ('chemistry','magnesium','Magnesium','Magnesium has the symbol Mg and atomic number 12. It is a light metal that burns with an intense white light.','Magnesium is important in chlorophyll and is used in lightweight alloys and flares.','Magnesium keeps both letters: Mg.'),
  ('chemistry','aluminium','Aluminium','Aluminium has the symbol Al and atomic number 13. It is lightweight, corrosion-resistant, and widely recyclable.','A thin protective oxide layer helps prevent the metal beneath from corroding further.','Aluminium begins with Al.'),
  ('chemistry','silicon','Silicon','Silicon has the symbol Si and atomic number 14. It is a semiconductor essential to computer chips and solar cells.','Silicon is abundant in Earth’s crust, commonly occurring in silica and silicate minerals.','Silicon chips use Si.'),
  ('chemistry','phosphorus','Phosphorus','Phosphorus has the symbol P and atomic number 15. It is essential in DNA, cell membranes, and energy transfer.','Phosphate compounds are also important fertilisers, though excess runoff can damage waterways.','Phosphorus is P.'),
  ('chemistry','sulfur','Sulfur','Sulfur has the symbol S and atomic number 16. It is a yellow non-metal used in sulfuric acid and many industrial processes.','Sulfur compounds contribute to the smell of rotten eggs, although pure sulfur itself is nearly odourless.','Sulfur starts with S.'),
  ('chemistry','chlorine','Chlorine','Chlorine has the symbol Cl and atomic number 17. It is a reactive halogen used to disinfect water.','In table salt, chlorine exists safely as chloride ions combined with sodium rather than as chlorine gas.','Chlorine needs two letters: Cl.'),
  ('chemistry','potassium','Potassium','Potassium has the symbol K and atomic number 19. It is a reactive metal essential for nerve and muscle function.','The symbol K comes from kalium; potassium ions are important electrolytes in the body.','Potassium’s symbol K comes from kalium.'),
  ('chemistry','calcium','Calcium','Calcium has the symbol Ca and atomic number 20. It is important in bones, teeth, muscle action, and cell signalling.','Calcium compounds also occur widely in limestone, chalk, and shells.','Calcium keeps its opening letters: Ca.'),
  ('chemistry','iron','Iron','Iron has the symbol Fe and atomic number 26. It is the principal metal in steel and is vital in haemoglobin.','The symbol Fe comes from the Latin ferrum; haemoglobin uses iron to carry oxygen.','Iron becomes Fe from ferrum.'),
  ('chemistry','copper','Copper','Copper has the symbol Cu and atomic number 29. It conducts electricity well and is widely used in wiring.','Its symbol comes from cuprum, and weathered copper can develop a green patina.','Copper is Cu from cuprum.'),
  ('chemistry','zinc','Zinc','Zinc has the symbol Zn and atomic number 30. It is used to protect steel from corrosion through galvanising.','Zinc is also an essential trace nutrient involved in enzymes and immune function.','Zinc drops the vowel: Zn.'),
  ('chemistry','silver','Silver','Silver has the symbol Ag and atomic number 47. It has the highest electrical conductivity of any element.','The symbol Ag comes from argentum; silver is used in jewellery, electronics, mirrors, and photography.','Silver is Ag from argentum.'),
  ('chemistry','tin','Tin','Tin has the symbol Sn and atomic number 50. It is a soft metal used in solder and protective coatings.','The symbol Sn comes from stannum; “tin cans” are usually steel coated with a thin layer of tin.','Tin is Sn from stannum.'),
  ('chemistry','iodine','Iodine','Iodine has the symbol I and atomic number 53. The thyroid uses iodine to make hormones that regulate metabolism.','Iodised salt helps prevent iodine deficiency; iodine vapour has a distinctive violet colour.','Iodine is the single letter I.'),
  ('chemistry','gold','Gold','Gold has the symbol Au and atomic number 79. It is dense, malleable, and unusually resistant to corrosion.','The symbol Au comes from aurum; gold’s stability makes it useful in jewellery and electronics.','Gold is Au from aurum.'),
  ('chemistry','mercury','Mercury','Mercury has the symbol Hg and atomic number 80. It is the only metallic element liquid at ordinary room temperature.','The symbol Hg comes from hydrargyrum, meaning liquid silver; mercury is toxic.','Mercury’s unusual symbol is Hg.'),
  ('chemistry','lead','Lead','Lead has the symbol Pb and atomic number 82. It is a dense, soft metal that is toxic to humans.','The symbol Pb comes from plumbum, the origin of the word plumbing.','Lead is Pb from plumbum.'),
  ('chemistry','uranium','Uranium','Uranium has the symbol U and atomic number 92. It is a heavy radioactive element used as nuclear fuel.','Uranium-235 can sustain a nuclear chain reaction, while uranium-238 is much more abundant.','Uranium uses U.'),
  ('chemistry','neon','Neon','Neon has the symbol Ne and atomic number 10. It is an unreactive noble gas that glows reddish-orange in discharge tubes.','Many colourful signs are casually called neon, but other gases create many of their colours.','Neon signs point to Ne.'),

  ('literature','Pride and Prejudice','Pride and Prejudice','Pride and Prejudice was written by Jane Austen. The novel follows Elizabeth Bennet as she navigates family pressure, social class, and her changing judgement of Mr Darcy.','First published in 1813, it combines romantic comedy with sharp social observation.','Elizabeth Bennet and Mr Darcy point to Jane Austen.'),
  ('literature','1984','1984','1984 was written by George Orwell. Its totalitarian state uses surveillance, propaganda, and controlled language to dominate citizens.','Published in 1949, it introduced enduring terms such as Big Brother, thoughtcrime, and doublethink.','Big Brother is watching: George Orwell’s 1984.'),
  ('literature','Things Fall Apart','Things Fall Apart','Things Fall Apart was written by Chinua Achebe. It portrays Okonkwo and an Igbo community confronting internal tensions and British colonial rule.','Published in 1958, it became one of the most influential works of modern African literature.','Okonkwo and Igbo life point to Chinua Achebe.'),
  ('literature','To Kill a Mockingbird','To Kill a Mockingbird','To Kill a Mockingbird was written by Harper Lee. Scout Finch narrates a story of childhood, prejudice, and her father’s defence of a Black man falsely accused in Alabama.','The 1960 novel centres moral courage while depicting the racism of the American South.','Scout and Atticus Finch point to Harper Lee.'),
  ('literature','The Great Gatsby','The Great Gatsby','The Great Gatsby was written by F. Scott Fitzgerald. Nick Carraway observes Jay Gatsby’s pursuit of wealth, status, and his idealised love for Daisy.','Set during the Jazz Age, the novel questions the promise and cost of the American Dream.','Gatsby, Daisy, and the Jazz Age mean Fitzgerald.'),
  ('literature','Moby-Dick','Moby-Dick','Moby-Dick was written by Herman Melville. Captain Ahab obsessively hunts the white whale that previously destroyed his ship and took his leg.','The 1851 novel combines an adventure at sea with reflections on obsession, nature, and knowledge.','Captain Ahab hunts Melville’s white whale.'),
  ('literature','Jane Eyre','Jane Eyre','Jane Eyre was written by Charlotte Bronte. Its independent heroine becomes governess at Thornfield Hall and forms a complicated bond with Mr Rochester.','Published in 1847, it combines social criticism, romance, and Gothic mystery.','Jane, Rochester, and Thornfield point to Charlotte Bronte.'),
  ('literature','Frankenstein','Frankenstein','Frankenstein was written by Mary Shelley. Victor Frankenstein creates a living being and then rejects it, with tragic consequences.','Published in 1818, it explores scientific responsibility, isolation, ambition, and what makes someone human.','The creator is Frankenstein; the author is Mary Shelley.'),
  ('literature','The Hobbit','The Hobbit','The Hobbit was written by J. R. R. Tolkien. Bilbo Baggins leaves the Shire to join a company of dwarves seeking their homeland and treasure.','The journey introduces Middle-earth figures including Gandalf, Gollum, and the dragon Smaug.','Bilbo, Smaug, and Middle-earth mean Tolkien.'),
  ('literature','The Catcher in the Rye','The Catcher in the Rye','The Catcher in the Rye was written by J. D. Salinger. Teenager Holden Caulfield narrates several unsettled days in New York after leaving school.','The novel is known for its distinctive voice and themes of alienation, grief, and authenticity.','Holden Caulfield points to J. D. Salinger.'),
  ('literature','Beloved','Beloved','Beloved was written by Toni Morrison. Set after the American Civil War, it follows Sethe as the trauma of slavery returns in haunting form.','The novel blends history, memory, and the supernatural to explore how oppression affects individuals and families.','Sethe and a haunting past point to Toni Morrison.'),
  ('literature','One Hundred Years of Solitude','One Hundred Years of Solitude','One Hundred Years of Solitude was written by Gabriel Garcia Marquez. It follows generations of the Buendia family in the fictional town of Macondo.','The novel is a landmark of magical realism, where extraordinary events enter everyday life without surprise.','Macondo and the Buendias mean Garcia Marquez.'),
  ('literature','The Handmaid''s Tale','The Handmaid''s Tale','The Handmaid’s Tale was written by Margaret Atwood. In the authoritarian Republic of Gilead, Offred is forced into reproductive servitude.','The novel explores power, gender, resistance, memory, and the political use of religious language.','Offred in Gilead points to Margaret Atwood.'),
  ('literature','The Old Man and the Sea','The Old Man and the Sea','The Old Man and the Sea was written by Ernest Hemingway. An ageing Cuban fisherman named Santiago struggles with a giant marlin far out at sea.','Its spare style explores endurance, dignity, defeat, and humanity’s relationship with nature.','Santiago and the marlin mean Hemingway.'),
  ('literature','Great Expectations','Great Expectations','Great Expectations was written by Charles Dickens. The orphan Pip receives unexpected wealth and tries to reinvent himself as a gentleman.','Its characters include Miss Havisham, Estella, Joe Gargery, and the escaped convict Magwitch.','Pip and Miss Havisham point to Dickens.'),
  ('literature','The Odyssey','The Odyssey','The Odyssey is traditionally attributed to Homer. The epic follows Odysseus’s long journey home to Ithaca after the Trojan War.','Its adventures include the Cyclops, Circe, the Sirens, and the loyalty of Penelope.','Odysseus returning to Ithaca means Homer.'),
  ('literature','The Trial','The Trial','The Trial was written by Franz Kafka. Josef K. is arrested and prosecuted by a remote authority without being told the nature of his crime.','Its unsettling bureaucracy helped make “Kafkaesque” a word for confusing, oppressive systems.','Josef K. and baffling bureaucracy mean Kafka.'),
  ('literature','Mrs Dalloway','Mrs Dalloway','Mrs Dalloway was written by Virginia Woolf. Over one day in London, Clarissa Dalloway prepares for a party while the novel moves through several minds.','Its stream-of-consciousness style explores time, memory, social life, and the aftermath of war.','One London day with Clarissa means Virginia Woolf.'),
  ('literature','The Stranger','The Stranger','The Stranger was written by Albert Camus. Meursault’s emotional detachment and a senseless killing lead to a trial focused as much on his character as his crime.','The novel is closely associated with Camus’s exploration of the absurd.','Meursault and the absurd point to Camus.'),
  ('literature','The Color Purple','The Color Purple','The Color Purple was written by Alice Walker. Through letters, Celie recounts abuse, separation, friendship, and her growth toward independence.','Set in the American South, the novel centres Black women’s lives, resilience, and mutual support.','Celie’s letters point to Alice Walker.'),
  ('literature','Brave New World','Brave New World','Brave New World was written by Aldous Huxley. Its future society maintains stability through conditioning, consumerism, caste, and the drug soma.','Unlike 1984’s rule through fear, this dystopia often controls people through comfort and distraction.','Soma and engineered castes mean Aldous Huxley.'),
  ('literature','Dracula','Dracula','Dracula was written by Bram Stoker. A group led by Professor Van Helsing confronts Count Dracula after his arrival from Transylvania.','The 1897 Gothic novel helped shape the modern image of the vampire.','Count Dracula and Van Helsing point to Bram Stoker.'),
  ('literature','The Picture of Dorian Gray','The Picture of Dorian Gray','The Picture of Dorian Gray was written by Oscar Wilde. Dorian remains outwardly young while his portrait records the effects of his choices.','The novel examines beauty, influence, morality, and a life devoted to sensation.','The ageing portrait points to Oscar Wilde.'),
  ('literature','The Bell Jar','The Bell Jar','The Bell Jar was written by Sylvia Plath. Esther Greenwood’s opportunities in New York give way to a severe mental-health crisis and treatment.','The semi-autobiographical novel uses the bell jar as an image of suffocation and confinement.','Esther under the bell jar means Sylvia Plath.'),
  ('literature','A Brief History of Time','A Brief History of Time','A Brief History of Time was written by Stephen Hawking. It introduces cosmology, black holes, time, and the origins of the universe for general readers.','Published in 1988, it became an unusually successful popular-science book.','Black holes for general readers point to Stephen Hawking.'),

  ('history','the Battle of Hastings','Battle of Hastings','The Battle of Hastings took place in 1066. William, Duke of Normandy, defeated the English king Harold II.','The victory began the Norman conquest and transformed English government, landholding, language, and architecture.','1066 is the famous date of Hastings.'),
  ('history','the signing of Magna Carta','Magna Carta','Magna Carta was sealed in 1215 after English barons rebelled against King John.','Although many clauses addressed medieval disputes, it became a lasting symbol of limited government and the rule of law.','King John and Magna Carta: 1215.'),
  ('history','the fall of Constantinople','Fall of Constantinople','Constantinople fell to the Ottoman Empire in 1453. Sultan Mehmed II captured the capital of the Byzantine Empire.','The conquest ended the Byzantine Empire and made the city a major Ottoman capital.','1453: Constantinople falls.'),
  ('history','Columbus first reached the Americas','Columbus reaches the Americas','Christopher Columbus first reached the Caribbean in 1492 while sailing for Spain.','The voyage began sustained European colonisation, bringing conquest, exchange, disease, and devastating consequences for Indigenous peoples.','“In fourteen hundred and ninety-two” recalls 1492.'),
  ('history','the Spanish Armada was defeated','Defeat of the Spanish Armada','The Spanish Armada was defeated in 1588 after attempting to support an invasion of England.','English attacks, difficult coordination, and severe weather all contributed to the fleet’s failure.','Armada: 1588.'),
  ('history','the Gunpowder Plot','Gunpowder Plot','The Gunpowder Plot was uncovered in 1605. Catholic conspirators planned to destroy Parliament and kill King James I.','Guy Fawkes was discovered guarding explosives beneath the House of Lords, leading to annual 5 November commemorations.','Remember, remember: 1605.'),
  ('history','the Great Fire of London','Great Fire of London','The Great Fire of London began in 1666 and burned for several days.','It destroyed much of the medieval City of London, though recorded deaths were surprisingly few.','The repeated sixes make 1666 easy to link with the fire.'),
  ('history','the American Declaration of Independence','American Declaration of Independence','The American Declaration of Independence was adopted in 1776 by the thirteen colonies.','It announced separation from Britain and articulated influential claims about equality and rights.','Fourth of July, 1776.'),
  ('history','the French Revolution began','Beginning of the French Revolution','The French Revolution began in 1789 amid financial crisis, inequality, and political conflict.','The storming of the Bastille on 14 July became its most famous opening symbol.','Bastille and revolution: 1789.'),
  ('history','the Battle of Waterloo','Battle of Waterloo','The Battle of Waterloo was fought in 1815. Allied armies defeated Napoleon Bonaparte in present-day Belgium.','The defeat ended Napoleon’s Hundred Days and his return to power after exile.','Napoleon’s final defeat: 1815.'),
  ('history','the first modern Olympic Games','First modern Olympics','The first modern Olympic Games were held in Athens in 1896.','The event revived the name and ideals of the ancient Greek games in a new international competition.','Modern Olympics begin in Athens, 1896.'),
  ('history','the Wright brothers first powered flight','First powered flight','The Wright brothers achieved their first controlled powered flight in 1903 near Kitty Hawk, North Carolina.','Orville piloted the first brief flight while Wilbur observed; later flights that day travelled farther.','Wright flight: 1903.'),
  ('history','World War I began','Beginning of World War I','World War I began in 1914 after the assassination of Archduke Franz Ferdinand intensified existing alliances and tensions.','The conflict expanded across Europe and beyond, lasting until 1918.','World War I: 1914 to 1918.'),
  ('history','the Russian Revolution','Russian Revolution','The Russian Revolution unfolded in 1917. The February Revolution ended tsarist rule, and the Bolsheviks seized power in October.','It transformed Russia and eventually led to the creation of the Soviet Union.','Two revolutions in one year: 1917.'),
  ('history','the Wall Street Crash','Wall Street Crash','The Wall Street Crash occurred in 1929 after a speculative stock-market boom.','It contributed to a wider collapse in confidence and became closely associated with the Great Depression.','Crash, then Depression: 1929.'),
  ('history','World War II began in Europe','Beginning of World War II in Europe','World War II began in Europe in 1939 when Nazi Germany invaded Poland.','Britain and France declared war on Germany two days later; the global conflict continued until 1945.','World War II: 1939 to 1945.'),
  ('history','India gained independence','Indian independence','India gained independence from British rule in 1947.','Independence was accompanied by partition into India and Pakistan, causing mass migration and terrible communal violence.','India and Pakistan emerge in 1947.'),
  ('history','the first human reached space','First human in space','Yuri Gagarin became the first human in space in 1961 aboard Vostok 1.','The Soviet cosmonaut completed one orbit of Earth in a flight lasting about 108 minutes.','Gagarin orbits Earth: 1961.'),
  ('history','the first Moon landing','First Moon landing','The first crewed Moon landing took place in 1969 during Apollo 11.','Neil Armstrong and Buzz Aldrin walked on the lunar surface while Michael Collins remained in orbit.','Apollo 11 landed in 1969.'),
  ('history','the Berlin Wall fell','Fall of the Berlin Wall','The Berlin Wall opened in 1989 after weeks of peaceful protest and political change in East Germany.','Its fall became the defining symbol of the Cold War’s end in Europe and preceded German reunification.','Berlin Wall falls: 1989.'),
  ('history','Nelson Mandela became president of South Africa','Mandela becomes president','Nelson Mandela became president of South Africa in 1994 after the country’s first fully democratic national election.','His presidency marked the formal end of apartheid rule and the beginning of a new constitutional era.','South Africa’s democratic turning point: 1994.'),
  ('history','the Euro was introduced as electronic currency','Introduction of the euro','The euro was introduced for accounting and electronic payments in 1999.','Euro banknotes and coins entered circulation later, in 2002.','Euro electronic in 1999, cash in 2002.'),
  ('history','Wikipedia launched','Wikipedia launches','Wikipedia launched in 2001 as a freely editable online encyclopedia.','Its volunteer-written model grew into one of the world’s largest and most visited reference works.','Wikipedia begins in 2001.'),
  ('history','the first iPhone was announced','First iPhone announced','The first iPhone was announced by Steve Jobs in 2007.','It combined a phone, widescreen media player, and internet device around a multi-touch interface.','iPhone announcement: 2007.'),
  ('history','the Paris Agreement was adopted','Paris Agreement','The Paris Agreement on climate change was adopted in 2015.','Countries agreed to pursue efforts to limit global temperature rise through national climate commitments.','Paris climate agreement: 2015.'),

  ('rivers','London','Thames','The River Thames flows through London. It runs across southern England and reaches the North Sea through a broad estuary.','Landmarks beside it include the Palace of Westminster, Tower Bridge, and the London Eye.','London’s river is the Thames.'),
  ('rivers','Paris','Seine','The River Seine flows through Paris. It winds past many central landmarks before continuing northwest to the English Channel.','The Eiffel Tower, Louvre, Notre-Dame, and historic riverbanks are closely tied to the Seine.','Paris and the Seine belong together.'),
  ('rivers','Rome','Tiber','The River Tiber flows through Rome. The city developed near a crossing of this central Italian river.','Roman tradition places the story of Romulus and Remus beside the Tiber.','Rome’s river is the Tiber.'),
  ('rivers','Cairo','Nile','The Nile flows through Cairo before reaching its delta and the Mediterranean Sea.','The river sustained ancient Egyptian agriculture and remains essential to life in modern Egypt.','Egypt and Cairo depend on the Nile.'),
  ('rivers','Vienna','Danube','The Danube flows through Vienna. It is Europe’s second-longest river and crosses or borders ten countries.','Vienna is one of four national capitals on the Danube, alongside Bratislava, Budapest, and Belgrade.','Vienna waltzes beside the Danube.'),
  ('rivers','Budapest','Danube','The Danube flows through Budapest, dividing historic Buda from Pest.','The Chain Bridge and Hungarian Parliament are among the city’s best-known riverside landmarks.','Buda and Pest meet across the Danube.'),
  ('rivers','New York City','Hudson','The Hudson River runs along the west side of Manhattan before reaching New York Harbor.','The river rises farther north in New York State and is named after explorer Henry Hudson.','West of Manhattan is the Hudson.'),
  ('rivers','Washington, D.C.','Potomac','The Potomac River flows beside Washington, D.C. before reaching Chesapeake Bay.','The river also forms sections of the boundary between Maryland and Virginia or West Virginia.','Washington sits on the Potomac.'),
  ('rivers','Dublin','Liffey','The River Liffey flows through central Dublin and enters Dublin Bay.','Many bridges cross it, and the river divides the city’s commonly described north and south sides.','Dublin’s river is the Liffey.'),
  ('rivers','Glasgow','Clyde','The River Clyde flows through Glasgow. Shipbuilding along its banks played a major role in the city’s industrial growth.','The Clyde continues west through an estuary toward the Firth of Clyde.','Glasgow shipbuilding means the Clyde.'),
  ('rivers','Bristol','Avon','The River Avon flows through Bristol and the Avon Gorge before reaching the Severn Estuary.','The Clifton Suspension Bridge spans the gorge high above the river.','Bristol and its gorge point to the Avon.'),
  ('rivers','Prague','Vltava','The Vltava flows through Prague. It is the longest river entirely within the Czech Republic.','Charles Bridge crosses the Vltava beneath Prague Castle.','Prague’s Charles Bridge crosses the Vltava.'),
  ('rivers','Warsaw','Vistula','The Vistula flows through Warsaw. It is Poland’s longest river and reaches the Baltic Sea near Gdansk.','The river crosses much of Poland from the southern mountains to the northern coast.','Warsaw and Poland’s longest river: Vistula.'),
  ('rivers','Lisbon','Tagus','The Tagus reaches a broad estuary beside Lisbon before entering the Atlantic Ocean.','It is the longest river on the Iberian Peninsula, rising in Spain and flowing west through Portugal.','Lisbon looks across the Tagus.'),
  ('rivers','Seville','Guadalquivir','The Guadalquivir flows through Seville in southern Spain.','Its navigable route helped make Seville a major port during Spain’s trade with the Americas.','Seville’s long river name is Guadalquivir.'),
  ('rivers','Florence','Arno','The Arno flows through Florence and later reaches the sea near Pisa.','Florence’s medieval Ponte Vecchio spans the river with shops built along it.','Florence and Ponte Vecchio mean the Arno.'),
  ('rivers','Baghdad','Tigris','The Tigris flows through Baghdad. Together with the Euphrates, it defines the historic region of Mesopotamia.','Baghdad developed beside this major river in present-day Iraq.','Baghdad’s river is the Tigris.'),
  ('rivers','Basel','Rhine','The Rhine flows through Basel where Switzerland meets France and Germany.','Basel’s position on the river has made it an important trading and transport centre.','Basel sits at a three-country bend of the Rhine.'),
  ('rivers','Cologne','Rhine','The Rhine flows through Cologne in western Germany.','Cologne Cathedral rises close to the river and the Hohenzollern Bridge carries rail traffic across it.','Cologne Cathedral overlooks the Rhine.'),
  ('rivers','Shanghai','Huangpu','The Huangpu River flows through Shanghai and separates the Bund from the skyscrapers of Pudong.','It is a tributary of the Yangtze estuary and a central feature of Shanghai’s port.','Shanghai’s Bund faces the Huangpu.'),
  ('rivers','Bangkok','Chao Phraya','The Chao Phraya flows through Bangkok and reaches the Gulf of Thailand.','Canals linked to the river helped earn Bangkok the nickname “Venice of the East”.','Bangkok’s river is the Chao Phraya.'),
  ('rivers','Delhi','Yamuna','The Yamuna flows through Delhi before joining the Ganges at Prayagraj.','It is one of northern India’s major rivers and has deep cultural and religious importance.','Delhi stands beside the Yamuna.'),
  ('rivers','Lahore','Ravi','The Ravi flows near Lahore and is one of the rivers of the Punjab region.','It crosses India and Pakistan before joining the Chenab within the Indus river system.','Lahore links to the Ravi.'),
  ('rivers','Melbourne','Yarra','The Yarra River flows through Melbourne and into Port Phillip Bay.','The city was founded beside the river, which remains central to Melbourne’s parks and waterfront.','Melbourne’s river is the Yarra.'),
  ('rivers','Brisbane','Brisbane River','The Brisbane River winds through the centre of Brisbane before entering Moreton Bay.','The Queensland capital and its river share the same name.','Brisbane is the easy same-name city and river pair.'),

  ('sport','LBW','LBW','LBW means “leg before wicket” in cricket. A batter may be dismissed when the body blocks a ball that would otherwise have hit the wicket.','The law considers where the ball pitched, where it struck, and whether it would have hit the stumps.','Leg before wicket belongs to cricket.'),
  ('sport','birdie','Birdie','A birdie in golf is a score of one stroke under par on a hole.','Two under par is an eagle, while one over par is a bogey.','Birdie is one under par in golf.'),
  ('sport','albatross','Albatross','An albatross in golf is a score of three strokes under par on one hole.','It is rarer than an eagle and is also called a double eagle in some countries.','The bigger the bird, the farther under par: albatross is minus three.'),
  ('sport','scrum','Scrum','A scrum is a rugby restart in which forwards bind together and contest possession after the ball is fed between the packs.','Scrums are especially structured in rugby union, with eight forwards from each team.','Packed forwards mean a rugby scrum.'),
  ('sport','try','Try','A try is the main scoring action in rugby, awarded for grounding the ball in the opponents’ in-goal area.','A try is followed by an opportunity to kick a conversion for additional points.','Ground the ball in rugby to score a try.'),
  ('sport','deuce','Deuce','Deuce in tennis means the score is tied at 40–40.','A player generally needs to win two consecutive points from deuce: advantage, then game.','Forty-all in tennis is deuce.'),
  ('sport','love','Love','Love means zero in tennis scoring. A score of 30–0 is announced as “thirty-love”.','The exact origin of the term is debated, despite a popular theory linking it to the French word for egg.','In tennis, love means nothing.'),
  ('sport','hat-trick','Hat-trick','A hat-trick is three notable successes by one player in a game, such as three football goals or three cricket wickets in consecutive deliveries.','The expression began in cricket when a bowler’s feat was traditionally rewarded with a hat.','Three successes make a hat-trick.'),
  ('sport','offside','Offside','Offside rules restrict attackers from gaining an unfair position near the opponents’ goal.','The exact definition differs between football, rugby, ice hockey, and other sports.','Too far ahead of play can mean offside.'),
  ('sport','home run','Home run','A home run in baseball allows the batter to circle all bases and score, usually after hitting the ball beyond the outfield fence in fair territory.','Any runners already on base also score on the play.','Hit it out and circle the bases: home run.'),
  ('sport','slam dunk','Slam dunk','A slam dunk in basketball is a shot made by forcefully putting the ball directly through the hoop with one or both hands.','Dunks combine reliable close-range scoring with athletic elevation and power.','Hands above the rim mean a basketball dunk.'),
  ('sport','touchdown','Touchdown','A touchdown is the main scoring play in American football, worth six points.','It is scored by carrying or receiving the ball in the opponent’s end zone.','End zone plus six points equals touchdown.'),
  ('sport','icing','Icing','Icing in ice hockey occurs when a player sends the puck across both the centre line and opponent’s goal line without it being touched.','Play is normally stopped and restarted with a faceoff in the offending team’s defensive zone.','A puck sent too far untouched is icing.'),
  ('sport','bullseye','Bullseye','The bullseye is the centre of a dartboard. The inner bull scores 50 points and the outer bull scores 25.','The inner bull is not the board’s highest possible single-dart score; treble 20 scores 60.','Darts: inner bull 50, treble 20 scores 60.'),
  ('sport','checkmate','Checkmate','Checkmate ends a chess game when the king is under attack and no legal move can remove the threat.','A king that is not in check but has no legal move produces stalemate instead.','No escape for the checked king means checkmate.'),
  ('sport','gambit','Gambit','A gambit is a chess opening in which a player offers material, commonly a pawn, to gain another advantage.','The compensation may be faster development, control of the centre, or an attack.','Offer a pawn for initiative: a chess gambit.'),
  ('sport','ippon','Ippon','Ippon is a full-point score in judo that ends the contest immediately.','It can be awarded for a decisive throw, a sustained hold-down, or a successful submission.','A perfect judo score is ippon.'),
  ('sport','peloton','Peloton','The peloton is the main group of riders in a road cycling race.','Riders save energy by sheltering from the wind behind others, making position within the group tactically important.','The cycling pack is the peloton.'),
  ('sport','bogey','Bogey','A bogey in golf is a score of one stroke over par on a hole.','A double bogey is two over, while a birdie is one under.','Bogey is one over par.'),
  ('sport','maiden over','Maiden over','A maiden over in cricket is an over from which the bowler concedes no runs charged against them.','Byes and leg byes may occur without spoiling the maiden because they are not credited against the bowler.','No runs conceded by the bowler: maiden over.'),
  ('sport','puck','Puck','A puck is the hard rubber disc used in ice hockey instead of a ball.','It slides rapidly across the ice and is struck with curved hockey sticks.','Ice hockey uses a puck.'),
  ('sport','frame','Frame','A frame is one unit of play in snooker, won by scoring more points than the opponent or receiving a concession.','Matches consist of an agreed odd number of frames so that one player can win a majority.','Snooker matches are divided into frames.'),
  ('sport','parry','Parry','A parry in fencing is a defensive blade action that blocks or deflects an opponent’s attack.','A successful parry is often followed immediately by a riposte, or return attack.','Block then riposte: fencing parry.'),
  ('sport','vault','Vault','A vault in gymnastics involves using speed and spring from an apparatus to perform a brief airborne routine over a vaulting table.','Judges assess difficulty, body position, control, and the landing.','Run, spring, fly, land: gymnastics vault.'),
  ('sport','spare','Spare','A spare in ten-pin bowling means knocking down all ten pins using both deliveries in a frame.','The score includes ten plus the number of pins knocked down by the next ball.','All pins in two rolls make a spare.')
),
matched as (
  select q.id as question_id, f.*
  from public.questions q
  join facts f on q.topic = f.topic
   and lower(q.prompt) in (
     lower(case f.topic
       when 'capitals' then 'What is the capital city of ' || f.subject || '?'
       when 'chemistry' then 'What is the chemical symbol for ' || f.subject || '?'
       when 'literature' then 'Who wrote ' || f.subject || '?'
       when 'history' then 'In which year did ' || f.subject || ' happen?'
       when 'rivers' then 'Which river flows through ' || f.subject || '?'
       when 'sport' then 'In which sport is the term ' || f.subject || ' used?'
     end),
     lower(case f.topic
       when 'capitals' then 'Which city is the national capital of ' || f.subject || '?'
       when 'chemistry' then 'On the periodic table, which symbol represents ' || f.subject || '?'
       when 'literature' then f.subject || ' was written by which author?'
       when 'history' then 'What year is associated with ' || f.subject || '?'
       when 'rivers' then f.subject || ' is associated with which river?'
       when 'sport' then 'The term ' || f.subject || ' belongs mainly to which sport?'
     end)
   )
  where q.pack_id = '00000000-0000-0000-0000-000000000101'::uuid
)
insert into public.question_learning_content (question_id, title, summary, context, memory_hook)
select question_id, title, summary, context, memory_hook
from matched
on conflict (question_id) do update set
  title = excluded.title,
  summary = excluded.summary,
  context = excluded.context,
  memory_hook = excluded.memory_hook;

do $$
declare
  enriched_question_count integer;
  enriched_fact_count integer;
  missing_count integer;
begin
  select count(*), count(distinct lower(content.summary))
  into enriched_question_count, enriched_fact_count
  from public.question_learning_content content
  join public.questions question on question.id = content.question_id
  where question.pack_id = '00000000-0000-0000-0000-000000000101'::uuid;

  select count(*) into missing_count
  from public.questions question
  where question.pack_id = '00000000-0000-0000-0000-000000000101'::uuid
    and not exists (select 1 from public.question_learning_content content where content.question_id = question.id);

  if enriched_question_count <> 500 or enriched_fact_count <> 250 or missing_count <> 0 then
    raise exception 'Expected 500 enriched variants, 250 unique facts, and no missing content; got %, %, and %', enriched_question_count, enriched_fact_count, missing_count;
  end if;
end
$$;
